action_id: trunk-upgrade-available
date: 2024-03-09 19:37:31
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1710013051
full_timestamp:
  nanos: 203909000
  seconds: 1710013051
trunk_version: 1.20.1
