action_id: trunk-upgrade-available
date: 2024-03-09 16:37:30
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1710002250
full_timestamp:
  nanos: 556314000
  seconds: 1710002250
trunk_version: 1.20.1
