action_id: trunk-upgrade-available
date: 2024-03-10 16:30:16
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1710088216
full_timestamp:
  nanos: 2102000
  seconds: 1710088216
trunk_version: 1.20.1
