action_id: trunk-share-with-everyone
date: 2024-03-09 15:55:56
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1709999756
full_timestamp:
  nanos: 261024000
  seconds: 1709999756
trunk_version: 1.20.1
